name: SkillsPlugin
version: 1.0.0
main: com.example.skillsplugin.SkillsPlugin
api-version: 1.20
author: SkillsPlugin Team
description: A comprehensive skill leveling system

commands:
  skills:
    description: View your skills
    usage: /skills [skillname]
    aliases: [skill, sk]

permissions:
  skills.use:
    description: Allows using the skills command
    default: true
  skills.reload:
    description: Allows reloading the config
    default: op
